
-- Structuur van  tabel safaribookings.accommodations wordt geschreven
CREATE TABLE IF NOT EXISTS `accommodations` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `website` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `website` (`website`)
) ENGINE=InnoDB AUTO_INCREMENT=3326 DEFAULT CHARSET=utf8;

INSERT INTO `accommodations` (`id`, `name`, `website`) VALUES
	(1, 'Deception Valley Lodge', 'https://test.safaribookings.com/dev-test-link/V4dTBmbHA2U0F5ak1ZTG1wMTdjNFE9PSIsInZhbHVlIjoiNnFham1iRlo5Z3I4UFJsVXlvdnlyU'),
	(2, 'Edo\'s Camp', 'https://test.safaribookings.com/dev-test-link/FFK1hyTTk5NTlTQWxBRnlCc01DL2c9PSIsInZhbHVlIjoiWTU4SktHeUtCN1Y1N3I5SVNpR3ZHS'),
	(3, 'Grassland Bushman Lodge', 'https://test.safaribookings.com/dev-test-link/RXOE1CQnhRd1d2c2xYWVVWWkhSUmc9PSIsInZhbHVlIjoiNmNsRWJkNHVmZ1VGWGpFeW1MNktmM'),
	(4, 'Haina Safari Lodge', 'https://test.safaribookings.com/dev-test-link/I2aWNJSVpGYXJXUnhpbS83ZjFXY0E9PSIsInZhbHVlIjoid3M0eGMxanplckdXem5zYURoZW1CZ'),
	(5, 'Kalahari Plains Camp', 'https://test.safaribookings.com/dev-test-link/Rqc3RNV0dkMVEzek1GeThFcndqWkE9PSIsInZhbHVlIjoiVTJ3WjlMdUQrZ295MG9EV3JzaGxhN'),
	(6, 'Motswiri Private Safari Lodge', 'https://test.safaribookings.com/dev-test-link/54VFhGQzdHcy9kODJkVy9XSTBXV3c9PSIsInZhbHVlIjoibnhNajk3YjJGenVuS29TVmVocVV2e'),
	(7, 'Tau Pan', 'https://test.safaribookings.com/dev-test-link/hPSzBGeUNiNWdiSTQ4d0ZnRHJkaUE9PSIsInZhbHVlIjoicDc0U3oyV1dKSVVqZmpaVEFYYlIvS'),
	(8, 'Sanctuary Chobe Chilwero', 'https://test.safaribookings.com/dev-test-link/orQm42cDJMZUEyYlB0ZHk3bzFjeGc9PSIsInZhbHVlIjoiU2xHLzVvZXBLUGtmMnFzZk5EamJBc'),
	(9, 'Chobe Game Lodge', 'https://test.safaribookings.com/dev-test-link/5PNWRIdy94WjNaWnJ1NkJ2U1U2Vnc9PSIsInZhbHVlIjoiMDkwVkNLQ1FoMHJ6aWMzUk9FOUhaV'),
	(10, 'Chobe Marina Lodge', 'https://test.safaribookings.com/dev-test-link/VnRzB5TlNzRFFwMStGODY5ZjlUTUE9PSIsInZhbHVlIjoiWmJNd0hlZEg3YnllZ3Y0RHJRTFBCR'),
	(11, 'Chobe Safari Lodge', 'https://test.safaribookings.com/dev-test-link/pUbWRTSHE3VjNDVG92R0pKdXdibnc9PSIsInZhbHVlIjoib3Z6b2VkbnlmODcyRjZrOStUNDMxS'),
	(12, 'Chobe Savanna Lodge', 'https://test.safaribookings.com/dev-test-link/F2N1pTaXhlRDJYbzAzUmN3TTFZTUE9PSIsInZhbHVlIjoiV200YitIZm1EaFRNTkh5aTZkeFhqY'),
	(13, '&Beyond Chobe under Canvas', 'https://test.safaribookings.com/dev-test-link/htekw0MWxheXRwbE1aSUhudU0rOUE9PSIsInZhbHVlIjoiRHlMakczOFBHSE12MFJEYU5BbDV1R'),
	(14, 'Elephant Valley Lodge', 'https://test.safaribookings.com/dev-test-link/hSM0lOZmVsWm8vNEtUdEpZUFNBZXc9PSIsInZhbHVlIjoiYXNyVUFSRFJ0a0VlYmZ0RkRtc3I5d'),
	(15, 'Ichingo Chobe River Lodge', 'https://test.safaribookings.com/dev-test-link/o1MW5jYUR3TE1LZEhndG52MklGSmc9PSIsInZhbHVlIjoicFNzb2NyVnZsOGNxaTM2aWhmRnhTW'),
	(19, 'Kubu Lodge', 'https://test.safaribookings.com/dev-test-link/s0UEQ1bnpxeG1yWERxNTNMUlZlUGc9PSIsInZhbHVlIjoiRTRyemF6MjB0OWl0cTgvbWxOc3duN'),
	(20, 'Liya Guest Lodge', 'https://test.safaribookings.com/dev-test-link/ZvRk1EZnlFMWR2U3Z4U3FKYWo5anc9PSIsInZhbHVlIjoiOFFnaVY3WmRDeWhGWXFjY0lPd1RkM'),
	(21, 'Cresta Mowana Safari Resort & Spa', 'https://test.safaribookings.com/dev-test-link/ltNVBwMnEyQytkTXExb2VRL1l1aEE9PSIsInZhbHVlIjoiS2F5YjdMMDZEckdOSlJFUFlFTnFBY'),
	(22, 'Muchenje Safari Lodge', 'https://test.safaribookings.com/dev-test-link/tMQkE1anlhODY1QU15RW9pSEVQWXc9PSIsInZhbHVlIjoiTGJSNi9LKzZoRUU5bjNXTGR2Wmx6c'),
	(24, 'Savute Elephant Lodge', 'https://test.safaribookings.com/dev-test-link/pJTHhkeWJEb1VrMHJ3M2trcDMzREE9PSIsInZhbHVlIjoieE9WYWc3RDhqcWMvOUl1dVhNc0NGQ'),
	(25, 'Savute Safari Lodge', 'https://test.safaribookings.com/dev-test-link/1tbGU1UjJncEVHMit3VE1ncVNrWXc9PSIsInZhbHVlIjoiV1RRay9EaDBXQlZUQzV1dStHSWNjW'),
	(26, '&Beyond Savute Under Canvas ', 'https://test.safaribookings.com/dev-test-link/FsUFFpcGVkVDM3aHE4SjZJTk5jYnc9PSIsInZhbHVlIjoiV3JrSzlRcFIrUGRGNEcwaUdoakZES'),
	(27, 'Senyati Safari Camp', 'https://test.safaribookings.com/dev-test-link/dsYkJLNHFlZEh5TDlQRSt6VzBlS0E9PSIsInZhbHVlIjoiR0NJT3hsZWxhR1FRQmRFNFB5SGZIb'),
	(28, 'Chobe River Lodge', 'https://test.safaribookings.com/dev-test-link/dtY3MzR3A2RVNqYytpaG1SZWJOc1E9PSIsInZhbHVlIjoibm9uYWJid0xmR0Z2TFc5MlJFVnFJQ'),
	(29, 'Thebe River Safaris Lodge', 'https://test.safaribookings.com/dev-test-link/I4b0lnMlhBL3FKWUd0WWxCc2N2eVE9PSIsInZhbHVlIjoiVmFuaXpIM2xVbGFqRGZIZ3E1akozZ'),
	(31, 'Water Lily Lodge', 'https://test.safaribookings.com/dev-test-link/R1WXUxZTBja0ZOejhGc2U4WHZXVXc9PSIsInZhbHVlIjoib21Va3pCUG9NK211aC92TTMrNm1hR'),
	(32, 'Zambezi Queen', 'https://test.safaribookings.com/dev-test-link/BZUGN3OTQ5Q0RISGZpYnljOHgwMWc9PSIsInZhbHVlIjoiUktBMzZYWnBpTS9wMnorU3lFR1dOd'),
	(33, 'San Camp', 'https://test.safaribookings.com/dev-test-link/xMalg5aUw1bGdiQTczVGN3Q3psL2c9PSIsInZhbHVlIjoiOEZYT2hHMzBzSU11NWd2TndRdkFjM'),
	(34, 'Camp Kalahari', 'https://test.safaribookings.com/dev-test-link/JZdGVvZVdyVUJWWndaaEZPR1NQSnc9PSIsInZhbHVlIjoid2NraEx3OStMNlN3Zm05Mm9hMWNyV'),
	(35, 'Meno A Kwena', 'https://test.safaribookings.com/dev-test-link/dxV2tPb2hwODdEcDlYWHc5aldMSlE9PSIsInZhbHVlIjoiaTZrckZHM25IZGVqM0ZqeDIvVVA5N'),
	(36, 'Planet Baobab', 'https://test.safaribookings.com/dev-test-link/1DazRNWHUzcHNpZkNtSytTWW81WUE9PSIsInZhbHVlIjoiQWRMOGxaQ05IRm1reEY0ZVNwUmNmc'),
	(37, 'Gweta Lodge', 'https://test.safaribookings.com/dev-test-link/RESU5HMDVQOUQwYklyaEZQZkZkbkE9PSIsInZhbHVlIjoidk42OEEwNnVrbE1abUdHVDc5L3hpM'),
	(39, 'Nxai Pan ', 'https://test.safaribookings.com/dev-test-link/YreEQ0L3ZkcGR0aHQ4K1M0WUlscXc9PSIsInZhbHVlIjoiSDlKa2hzdFRZbnNmV1Y3Nm8xRENkT'),
	(40, 'Abu', 'https://test.safaribookings.com/dev-test-link/RZSXQ5bWQ0eEVZUDZhM05OR0h3UFE9PSIsInZhbHVlIjoiQ3h4ZTYrbkU1QU40VzUxTVJadFMrM'),
	(41, 'Baines\' Camp', 'https://test.safaribookings.com/dev-test-link/dEVzNRWXJQajVheCs5VlRaUzd1VGc9PSIsInZhbHVlIjoiQ085L2Z1WjVvaU5hc0R0OTA3b2RPV'),
	(42, 'Sable Alley', 'https://test.safaribookings.com/dev-test-link/d4VmU3VEJYS0owREhNMXg2ZWN1a1E9PSIsInZhbHVlIjoiS2NJNUQ5NmRlNEZvMW5vU0RVUGlGR'),
	(43, 'Camp Moremi', 'https://test.safaribookings.com/dev-test-link/pGbGJ5Z0JxYTdtN1NMZm1sVTBLZmc9PSIsInZhbHVlIjoibUR5S09wUndVdW9uTXNnaVEzQjhaL'),
	(44, 'Camp Okavango', 'https://test.safaribookings.com/dev-test-link/xkeWdrM1ZnZjhrbzB2c1doOCtseWc9PSIsInZhbHVlIjoiOW9neWY5SjVsR2RVTlNHWXpoZzVqS'),
	(45, 'Sanctuary Chief\'s Camp', 'https://test.safaribookings.com/dev-test-link/U0bVgzSlM0Zm5tdEJNYjBJZ3B6T1E9PSIsInZhbHVlIjoiUzRlcjlRRnUxWXlLNFg4WkF2UGtKT'),
	(46, 'Chitabe Camp', 'https://test.safaribookings.com/dev-test-link/x0OFVSam9rNFNQMWI4Snp5YWRzOGc9PSIsInZhbHVlIjoidkoxSnFjNUlNVDlDZUVMcHVkY0hna'),
	(47, 'Chitabe Lediba', 'https://test.safaribookings.com/dev-test-link/9VQUdISlZmRU5JREZYSE4wTGV0cGc9PSIsInZhbHVlIjoiV3psMDBBdFJ5STI0VzZjQUpMWFJjR'),
	(48, 'Delta Camp', 'https://test.safaribookings.com/dev-test-link/dDNXk5MGtyVzJ5VWRnSFpCMjU0OXc9PSIsInZhbHVlIjoiQXkrMi9KY0FQbW03Qkc4bEt2ekxNS'),
	(49, 'Duba Plains', 'https://test.safaribookings.com/dev-test-link/xMbTF6TE1FdDI1bEM5QVBmeDEraUE9PSIsInZhbHVlIjoiWkJmSlJqdUVvMlBIbm9vUlg0ejBCY'),
	(50, 'Eagle Island Lodge', 'https://test.safaribookings.com/dev-test-link/JRZ1VrMnM2WE5rZ0JsYXZUckhKUkE9PSIsInZhbHVlIjoieER4S0E1dzMrc1pLMEFLd2czZzhuN'),
	(51, 'Footsteps Camp', 'https://test.safaribookings.com/dev-test-link/FCTHlZZ0g3dDNSc1VJUzZUbzRSbkE9PSIsInZhbHVlIjoiV3pCSHdyaWIveDBxSHA4WXViM1lhb'),
	(52, 'Gudigwa Camp', 'https://test.safaribookings.com/dev-test-link/BtOVhURlpES1FWbGxUN09YVll6OVE9PSIsInZhbHVlIjoidmI5b1RkaldycGZoSnRFL3VRQWY0U'),
	(53, 'Jacana Camp', 'https://test.safaribookings.com/dev-test-link/dEVW8xd3QxUCs2MEt4SGRFMFpqbnc9PSIsInZhbHVlIjoidUFrRmhiQ2RtVzQwVG9wMHpkWmtIZ'),
	(54, 'Jao', 'https://test.safaribookings.com/dev-test-link/RPL1l0L1U5aXF4c2NXU0R6TUJIaEE9PSIsInZhbHVlIjoiYk9UTVpWdlAvMVQ1Q2lWbFdwdUZCT'),
	(55, 'Kanana', 'https://test.safaribookings.com/dev-test-link/hoNjlDM1Q0V0g0K01Dem1vb1ZXUGc9PSIsInZhbHVlIjoiMzMxc0x0VVpZdVJoUEYvQXMvWlBpb'),
	(57, 'Khwai River Lodge', 'https://test.safaribookings.com/dev-test-link/NoL01OOTJmTjVrNmErRVF1eDFJTXc9PSIsInZhbHVlIjoiQkF4Z3BRdi9oazBUYk1UbTJMOFdWS'),
	(58, 'Khwai Tented Camp', 'https://test.safaribookings.com/dev-test-link/A3Y1N2U0pQQzB5QnZkeUsyQ0tXcHc9PSIsInZhbHVlIjoiSmFrQ1RPaVhISFhBK3YvNGltVVBaY'),
	(59, 'Kujwana Camp', 'https://test.safaribookings.com/dev-test-link/JoUDIrZ2VMR1lDcVZ5VGttcE9tUXc9PSIsInZhbHVlIjoicXQ1YWhYaEJMS0VEZUZnbzJ3cE5Bb'),
	(60, 'Kwara', 'https://test.safaribookings.com/dev-test-link/NlUWtpMFpsejNsVHhiRjJjcGlqbXc9PSIsInZhbHVlIjoicGs2a3EwU2xvUWJLNmRsN1lxWmpZV'),
	(61, 'Kwetsani', 'https://test.safaribookings.com/dev-test-link/M0U3NmbVFYRSt2bjZZbnZKbXZVYnc9PSIsInZhbHVlIjoiOUxlMitYYWp1czdmTlJwd2xncGJkV'),
	(62, 'Little Kwara', 'https://test.safaribookings.com/dev-test-link/9UOUY5dG15T1p1Y1JSNzFHOFpMSWc9PSIsInZhbHVlIjoib3pZNFhLdzRNa0pLZW02OS9oSGhWR'),
	(63, 'Little Mombo', 'https://test.safaribookings.com/dev-test-link/dzdHhsTGhTVmRoUHBhTjhkUGd1d1E9PSIsInZhbHVlIjoiellWK3VQZW9WU0JlMnArK1gzbFFNN'),
	(64, 'Little Vumbura', 'https://test.safaribookings.com/dev-test-link/ttRHY1SWNxWklySnJGdE51M3NPK2c9PSIsInZhbHVlIjoiOGd5Ymd2Q0dUWlhxWDhjOEZ6V01BW'),
	(65, 'Macatoo Camp', 'https://test.safaribookings.com/dev-test-link/FjcDUxNlRXU253bjhiTjZiWi9ubFE9PSIsInZhbHVlIjoiRFlHd2tvRVl4ckZONmRzOWR4WXZJN'),
	(66, 'Mapula Lodge', 'https://test.safaribookings.com/dev-test-link/dRbWh5R0dqeFRJOHpGc3ZXTjlxclE9PSIsInZhbHVlIjoiaTRiY0Q2SWpFVHE1OWRTNDNWc1hlT'),
	(67, 'Mokolwane Camp', 'https://test.safaribookings.com/dev-test-link/plMDNXZ3JabGFCVVVRNXhWRmpaMmc9PSIsInZhbHVlIjoiTDlDV3VIYUozdHRJellPN3RyMHI0T'),
	(68, 'Mombo', 'https://test.safaribookings.com/dev-test-link/ZkbG9KOTJRd1NVeE50N0tBa1FYR2c9PSIsInZhbHVlIjoiSU0xTk1wcE9nY0hGMDkxZXhEblZCN'),
	(69, 'Moremi Crossing', 'https://test.safaribookings.com/dev-test-link/BGaG5sOU5wVUpWd21yVDB3Z1A5OXc9PSIsInZhbHVlIjoiTTIycjNTR0lpV2NxeXJvQnBPNHhpN'),
	(71, '&Beyond Nxabega Okavango Tented Camp', 'https://test.safaribookings.com/dev-test-link/VBSWF4MkxZWUljQnpnbG9TWFV5Unc9PSIsInZhbHVlIjoidHBjOW1ja0loMVprbVF1Qy9MVC9Xb'),
	(72, 'Oddballs\' Enclave', 'https://test.safaribookings.com/dev-test-link/5pSTErd2xkeTRpL1hES1pYM0Z6c0E9PSIsInZhbHVlIjoielBjb3NPNElHWWdyQzhTdXBRbDFoV'),
	(74, 'Okuti', 'https://test.safaribookings.com/dev-test-link/VHaUNublhDU3dWcCtQV0VlQWVJdnc9PSIsInZhbHVlIjoicDJSNnNFS2ZGWmFDUjhnOVhra3l2Z'),
	(75, 'Pom Pom Camp', 'https://test.safaribookings.com/dev-test-link/FkN1NiQ09YOXNRMkxtdTVsalArY0E9PSIsInZhbHVlIjoiMjlrWWQ1YjhQd3BLRnU5c3JuSUR2T'),
	(76, 'Sleep Out', 'https://test.safaribookings.com/dev-test-link/c0SnZiTUszZ2tNMkZCMDlSRlliTlE9PSIsInZhbHVlIjoiZjZicytJVVI4bTRiOEVMeFdqd0JKU'),
	(77, '&Beyond Sandibe Okavango Safari Lodge', 'https://test.safaribookings.com/dev-test-link/UxdjNXM3pKa29sMnBkem5GbDcrbnc9PSIsInZhbHVlIjoiS003dVp2T2c0c2RpZ1FNL3NFOTlFV'),
	(78, 'Sango Safari Camp', 'https://test.safaribookings.com/dev-test-link/BiZzliTHFMek00WGtlZ2NuTTlnQ1E9PSIsInZhbHVlIjoiL0lsV2FzQ1B3WGZIRmQwVm9DTUozY'),
	(80, 'Santawani Lodge', 'https://test.safaribookings.com/dev-test-link/5Mb2MydlNESHdlODVwNmRVcm5MUGc9PSIsInZhbHVlIjoiTnRxUlpRMTBUc3lhaUFNVmx3K3NWd'),
	(81, 'Seba Camp', 'https://test.safaribookings.com/dev-test-link/JZdFM3UE9FRWV5Y3RDMXZXNnpZR0E9PSIsInZhbHVlIjoiYVpnN2paM3N3OWtZS2Vsd3lDUEdqW'),
	(82, 'Shinde', 'https://test.safaribookings.com/dev-test-link/Q5Z0tBZ1V2OGd3VFNwakthMmJpeHc9PSIsInZhbHVlIjoieng3NnVwamdqK3cxK1czZjF2WHg0Y'),
	(83, 'Sanctuary Stanley\'s Camp', 'https://test.safaribookings.com/dev-test-link/5sc0NpdFl1NWhWNmlyVXltaHJST2c9PSIsInZhbHVlIjoiWkRpdGlVN1c2aUpWbnlLZHN0R01PS'),
	(84, 'Tubu Tree', 'https://test.safaribookings.com/dev-test-link/FEWEdpNG1xLzIyUTFqZWErVEpWckE9PSIsInZhbHVlIjoiYjFVSlVIQ0pQNWdpWTVBcEFIT2lIT'),
	(85, 'Vumbura Plains', 'https://test.safaribookings.com/dev-test-link/hMQS9jUGZoaVNzRXFvYk41THFENkE9PSIsInZhbHVlIjoidW5iNHNZdVdLbE01UlhpQng5SU55a'),
	(86, 'Camp Xakanaxa', 'https://test.safaribookings.com/dev-test-link/kwd05tYXg1RmxDV001Q2ExNklFN0E9PSIsInZhbHVlIjoiNm9hK2lNVGVkV1FlV1FrR2J1ZE5ES'),
	(87, '&Beyond Xaranna Okavango Delta Camp', 'https://test.safaribookings.com/dev-test-link/FheUdZb3N2blo2NVRpSkZQMnl3RVE9PSIsInZhbHVlIjoidmcwV2I5Qm1TVUpmVnNBRVVRT2VxT'),
	(88, 'Xigera Safari Lodge', 'https://test.safaribookings.com/dev-test-link/BxOEhqZ1pqSmowcTVVQWt1b2VRbGc9PSIsInZhbHVlIjoickFVS0Yxa0lIT0NNM2FPVDZTelhRR'),
	(89, 'Xudum Okavango Delta Lodge', 'https://test.safaribookings.com/dev-test-link/pnRHBEOXlQenlVK3hRQktNTkZTTlE9PSIsInZhbHVlIjoiS2xUbkVEV3JPd3ZRcFpsMjBFVVZ5N'),
	(90, 'Xugana Island Lodge', 'https://test.safaribookings.com/dev-test-link/dIZkFJemNVd091bGVqdXowVlg0Y3c9PSIsInZhbHVlIjoiakpPZVZDbmJRMjdLLytTdnZWOFJJb'),
	(92, 'Mashatu Lodge', 'https://test.safaribookings.com/dev-test-link/p6WEhkQU0yVmt3azVtdVl1SHpnQUE9PSIsInZhbHVlIjoiOElOQUhENUhQR2dKNXp3OG9oYTlXY'),
	(93, 'Mashatu Tent Camp', 'https://test.safaribookings.com/dev-test-link/hMbWZqMXM5eXFLbDNSZ3o0ZDhFMGc9PSIsInZhbHVlIjoiVWIrc3BTUG05bU5kaTBpejdKRTJUa'),
	(94, 'Tuli Safari Lodge Mashatu', 'https://test.safaribookings.com/dev-test-link/xtOEN0NS9yQU1NeDFRRmhaenhhVVE9PSIsInZhbHVlIjoiNmNEYnFkd2ZTSnNpaHVFbk9uYklrV'),
	(95, 'Mokolodi Traditional Rest Camp', 'https://test.safaribookings.com/dev-test-link/hwbEthdmJSc1AyZXFxRHFQa1oxMFE9PSIsInZhbHVlIjoiSFFtclFBaFdtamNNQlF1dFFPR1R2a'),
	(96, 'Mokolodi Chalets', 'https://test.safaribookings.com/dev-test-link/hDa3JyVlpjeEFFcTNYVXNOMEJvZ1E9PSIsInZhbHVlIjoiUG9XN1hLbnpTQWFVcjFtNE1QeHhyb'),
	(97, 'Lagoon', 'https://test.safaribookings.com/dev-test-link/JpY2gxeWtsV3RVL2ZqdHpZaTBORUE9PSIsInZhbHVlIjoid2drTm5TTzBUWkwxV1ZVZFk1TzZEZ'),
	(98, 'Lebala', 'https://test.safaribookings.com/dev-test-link/BNeTVQN0p6Ni9YN3lmK0F4d3FyMlE9PSIsInZhbHVlIjoiaGN6NzdpTVE3S01XcTM4QTZaMXZrT'),
	(99, 'King\'s Pool', 'https://test.safaribookings.com/dev-test-link/VXMEkydzdzR09MbEt0c3NSVndtNWc9PSIsInZhbHVlIjoiT3RQUkN6bVBpUXd1MFBrOXlYVVVUT'),
	(100, 'DumaTau', 'https://test.safaribookings.com/dev-test-link/BpVndrQVRmOS9oSS91WWNTRTAwSUE9PSIsInZhbHVlIjoiN003NzZIRHBuV3ErQktJUGNLb0x0M'),
	(101, 'Linyanti Bush Camp', 'https://test.safaribookings.com/dev-test-link/NjalA4VloyVXl4RURlV3FZSThRUXc9PSIsInZhbHVlIjoiR2JCNnl5Vk5ZWnlKUVdkOEE0aXNLd'),
	(102, 'Linyanti Ebony', 'https://test.safaribookings.com/dev-test-link/J1eGh1MjAyd2duYXNtNHdqQ1gxZ3c9PSIsInZhbHVlIjoiTWpKMmlzYU9PL1Vlb3pRZ0NyNTV1Q'),
	(104, 'Savuti Camp', 'https://test.safaribookings.com/dev-test-link/9vd1dCZWx4d2t0QmpkNWFqcmdoK1E9PSIsInZhbHVlIjoiUEVNbHE4TjhHamFoL3g1QTlFYU8wW'),
	(106, 'Selinda Camp', 'https://test.safaribookings.com/dev-test-link/had3ZMdUdiOEJCekJzeHMyZDQ2bEE9PSIsInZhbHVlIjoiakhaWFZMd0U1Z21kVU5oeEt3MmZDV'),
	(107, 'Zarafa Camp', 'https://test.safaribookings.com/dev-test-link/RENHRWUlFMZENyWjcwTkVVKzU5Ync9PSIsInZhbHVlIjoiSVNneDJIYlVoY1RaZUJkaFhWM2dZQ'),
	(108, 'Gibb\'s Farm', 'https://test.safaribookings.com/dev-test-link/1JakNNMEg0ekV5aGRuaXpjckJxeFE9PSIsInZhbHVlIjoicEtpdjdBOW5PYk1xQ2xwM1J2RjJ1N'),
	(109, 'Lemala Ngorongoro', 'https://test.safaribookings.com/dev-test-link/ZjZlVnUk1KcTZ0V3JVbzd5alZjTmc9PSIsInZhbHVlIjoiTjZacUQwa1dBTS9ROVpMK1NiQndkR'),
	(110, '&Beyond Ngorongoro Crater Lodge', 'https://test.safaribookings.com/dev-test-link/lkY2tHeFFWZ3FxUFNBcU1DRDFEZXc9PSIsInZhbHVlIjoiZWFnOE1ReWN6Rk1WcXJWNldLOGpWW'),
	(111, 'Ngorongoro Farm House', 'https://test.safaribookings.com/dev-test-link/5uNVBEV3NYS1ErdmRtOVVzdjBNNnc9PSIsInZhbHVlIjoiQjAzaTNLV1U1VDRETzRnNk5jQTQ3e'),
	(112, 'Ngorongoro Serena Safari Lodge', 'https://test.safaribookings.com/dev-test-link/diRm96a1ZBbVI3TlpoQ3ZZRXRjaFE9PSIsInZhbHVlIjoiRkllai9JMlY2QkRYU2ZDMzlSTTRPZ'),
	(113, 'Ngorongoro Sopa Lodge', 'https://test.safaribookings.com/dev-test-link/FqTzh3dTM5R1BmdFE5VGJMZVUzcFE9PSIsInZhbHVlIjoiV1NmT1RlbEFPeFNlejJSSzA4bnNUV'),
	(115, 'Ngorongoro Wildlife Lodge', 'https://test.safaribookings.com/dev-test-link/doTnNuM2UyYmtkckRrRWpaczl3T2c9PSIsInZhbHVlIjoibE5KNDlMc0Zxc3ppVk5JeExWSmdpe'),
	(116, 'Rhino Lodge', 'https://test.safaribookings.com/dev-test-link/9GcitObXJNZHAzYjNJTXZTeXJFV1E9PSIsInZhbHVlIjoiT0ZHMG9hdUFYMnlSNXdPSC93OFVCZ'),
	(117, 'The Manor at Ngorongoro', 'https://test.safaribookings.com/dev-test-link/9Wb3grWXdzZE1tOE40bStnTXMra2c9PSIsInZhbHVlIjoiK2gzNkQvc1ZLVktzTDBQT0xvbjgzZ'),
	(118, 'Highview Hotel', 'https://test.safaribookings.com/dev-test-link/QxdU9lVHBNUStDTWZYTWtPSjE1Z1E9PSIsInZhbHVlIjoiU0UyZlVHMmo2bU9zNE5nZWZqaWcye'),
	(119, 'The Plantation Lodge', 'https://test.safaribookings.com/dev-test-link/l0Y1YrNitnZHY1TW8zVUlHVHU1MHc9PSIsInZhbHVlIjoiK1BTTnNuMitSeExoVFY2akdJQTROM'),
	(120, 'Octagon Lodge', 'https://test.safaribookings.com/dev-test-link/FvbGJvcjZvdU9ZQ3BUanAveTNaT0E9PSIsInZhbHVlIjoiMmVjRFRzUHcwMFFSSzltWWpMWGxRb'),
	(121, 'Tloma Lodge', 'https://test.safaribookings.com/dev-test-link/FNYmp2OWRPeENGSDNoWlp4aEVBTHc9PSIsInZhbHVlIjoiMnYwaEZZalZMVmlXekh0OURmS1k0b'),
	(122, 'Ngorongoro Wild Camp', 'https://test.safaribookings.com/dev-test-link/ZJWkJpVDZ0bVY1S3hnOGd3enZqeUE9PSIsInZhbHVlIjoiak54Tk9uNG14NDAxWUxOK2RhWkhKM'),
	(124, 'Beho Beho', 'https://test.safaribookings.com/dev-test-link/I1VnJVa0FEV0RsRFBLOEt5QTMrZ3c9PSIsInZhbHVlIjoiTnVzYlc2MjFUclBVMjNkVXZEc0RFW'),
	(125, 'Sand Rivers Selous', 'https://test.safaribookings.com/dev-test-link/p6YUVtaVlTOHIrRG85Q1BWNlF5d2c9PSIsInZhbHVlIjoid05NdnBEbitsSjRYcjAzVUVobDdtQ'),
	(126, 'Kiba Point Selous', 'https://test.safaribookings.com/dev-test-link/JqOUV3QWh4dUQ4Q3ppNStZczEzeVE9PSIsInZhbHVlIjoiRFJBTkt6MFN2OEVRdmdBK2FCbFVFe'),
	(128, 'Selous Impala Camp', 'https://test.safaribookings.com/dev-test-link/M5VWJiUytmQ2gyVmZTM05pazE4U2c9PSIsInZhbHVlIjoic1dGZzAzVVMxTjc4c2FPSGtoaUh3Z'),
	(129, 'Lake Manze Tented Camp', 'https://test.safaribookings.com/dev-test-link/43MmdCbEl4TWpqY3VyS2h5V2NzMXc9PSIsInZhbHVlIjoiY2tWYXI1THNNMnJzZUYwWXJaVnlNc'),
	(130, 'The Retreat Selous', 'https://test.safaribookings.com/dev-test-link/ZMdTA0WHRqWi9FaVJSOVVmdHRpVEE9PSIsInZhbHVlIjoiMHliUHVUbDlkUTcydzdVWWlYSlM1U'),
	(131, 'Azura Selous', 'https://test.safaribookings.com/dev-test-link/lFMFQ3MDRHZVh3elF0MEZ0ZlYxTEE9PSIsInZhbHVlIjoicHJUMHBZRGd0bUdWZlZZWFdLbE9FV'),
	(132, 'Selous River Camp', 'https://test.safaribookings.com/dev-test-link/81akZKZGJtMkxnelZIRlE2QTF3aVE9PSIsInZhbHVlIjoiVGFLa1lKc1JHTUluZjNkZEpDT09vZ'),
	(133, 'Selous Wilderness Camp', 'https://test.safaribookings.com/dev-test-link/1lMEtZY0ZRVmxQYVg4ZDRnQkJLb0E9PSIsInZhbHVlIjoidlQ1NUNxY2lHNVVuajF4WlNHZkJvY'),
	(134, 'Selous Riverside Safari Camp', 'https://test.safaribookings.com/dev-test-link/JReDFBbGtlcEIwZElsUUc2aXVyRFE9PSIsInZhbHVlIjoiODFtMUN4Qm5mVVdJaXVqUHQ2VklTW'),
	(135, 'Rufiji River Camp', 'https://test.safaribookings.com/dev-test-link/55azBJZnE5L08yU2pRWnB0dVZkc2c9PSIsInZhbHVlIjoieXBUdG1pc1R0NmgrVXNqbWhqQjE2V'),
	(136, 'Serena Mivumo River Lodge', 'https://test.safaribookings.com/dev-test-link/1mRThySzREUTR3THAzV3VGQUJqSGc9PSIsInZhbHVlIjoiZFhkaXhjQnY1QldoMEZPa3k0ZlU1R'),
	(138, 'Selous Mbega Camp', 'https://test.safaribookings.com/dev-test-link/VyR0ljSGVMVDJldzlET1RLR2kwRmc9PSIsInZhbHVlIjoiaEFVaVVNR2J1RlZIZTNrcXZDNVE5a'),
	(141, 'Sable Mountain Lodge', 'https://test.safaribookings.com/dev-test-link/hmMjVaYTUxUmRnMW9yWkd4UGlvL2c9PSIsInZhbHVlIjoibVMrSXRvcGJkaDltVVNiVWg4MjF6Y'),
	(142, 'Asanja Moru', 'https://test.safaribookings.com/dev-test-link/YxdHZRV0ZCT0pRU2hpVE1YeFJaeFE9PSIsInZhbHVlIjoiaVgyMWV5a201QzdpYVJMcDk5U1FIR'),
	(143, 'Taasa Lodge', 'https://test.safaribookings.com/dev-test-link/JUaGFYam96ZE9jdmlML3B2UlJ4bVE9PSIsInZhbHVlIjoibzdKYUI1a2xNTEZDeEQ5U1JXU3I3V'),
	(144, 'Dunia Camp', 'https://test.safaribookings.com/dev-test-link/lya1RiTVQ5eFZjSUo0VTlVcnJKNVE9PSIsInZhbHVlIjoiS2hhckd6V3FEdmwvbFhqM1hvOWtXM'),
	(145, 'Grumeti Migration Camp', 'https://test.safaribookings.com/dev-test-link/hWMm5udmJHd3dpV0l2OTgzTDQ0OUE9PSIsInZhbHVlIjoiYjUvOCs0b0RWeFJIeWlRb0wxUDYrZ'),
	(146, 'Singita Faru Faru Lodge', 'https://test.safaribookings.com/dev-test-link/9wclhsUXRPSzNNTHV6U29oc2ltY0E9PSIsInZhbHVlIjoicGVsOUFFSHVyYVJOODYrVUJidnJKT'),
	(147, '&Beyond Grumeti Serengeti Tented Camp', 'https://test.safaribookings.com/dev-test-link/lWMEtGa3k4SnFSM21YZktiRWpxQVE9PSIsInZhbHVlIjoiZEsxVXMwWVVFcEJ3aWV5R05QaVBFU'),
	(148, 'Ikoma Tented Camp', 'https://test.safaribookings.com/dev-test-link/RISUZ5N0xsanZZVGtkcTd0ZXpsQ3c9PSIsInZhbHVlIjoiTCtyQ203OW9BZ05EMTMwSlBwd3lkN'),
	(149, 'Ikoma Safari Camp', 'https://test.safaribookings.com/dev-test-link/NXc3ZXMmhsczhHemhUNm0yejRBemc9PSIsInZhbHVlIjoiYkNUb2RHMmtvd1hnNkNhUzVIdTE0W'),
	(150, 'Ikoma Wild Camp', 'https://test.safaribookings.com/dev-test-link/YxeXZmQzhhNmMrVThTc2d3VXlRTEE9PSIsInZhbHVlIjoiRkF3dXEzclVmRlFRakkzTWozbUhra'),
	(152, 'Kirawira Serena Camp', 'https://test.safaribookings.com/dev-test-link/pGcWMxSHFUaXVRTDBkY0loUUc1THc9PSIsInZhbHVlIjoiREQzM0tqOFZQeHdPWXdTenV6MW9Ic'),
	(153, '& Beyond Klein\'s Camp', 'https://test.safaribookings.com/dev-test-link/NtMDgzdEFWb0cwQU9xZXFJeWMzU3c9PSIsInZhbHVlIjoiSkVWcDBrT2VEUjVSZGlWVnRtQkxiY'),
	(154, 'Sanctuary Kusini', 'https://test.safaribookings.com/dev-test-link/9IR2l0MWI4Ynpxd0dCWEpWZXh1MEE9PSIsInZhbHVlIjoiNG9hMWxoUE1YbVVJTXpteGx0WFpBK'),
	(155, 'Lake Masek Tented Lodge', 'https://test.safaribookings.com/dev-test-link/F6WFZQbmZVNFhrTjlZWjNlMHlIbVE9PSIsInZhbHVlIjoiMTdEYXovcVF5ejJ0VkF4eS9vUDJZM'),
	(156, 'Lamai Serengeti', 'https://test.safaribookings.com/dev-test-link/pwYU1MNFVjWW5UdkJ2b2t5N3lmdmc9PSIsInZhbHVlIjoiZHlvUlpGK1hxb0hQWForMlNpVmdmM'),
	(157, 'Lemala Ewanjan Tented Camp', 'https://test.safaribookings.com/dev-test-link/4zVUtudE1xYXJiVzlUQm9sT0hKRGc9PSIsInZhbHVlIjoiZ01ha1RaR3gzdTVNTi92MEpqSjlae'),
	(158, 'Lemala Mara & Ndutu Tented Camp', 'https://test.safaribookings.com/dev-test-link/FKM1BrYklXM0VoeDV5TEVtenE4UkE9PSIsInZhbHVlIjoic3RSdVMzYStEVHNZZ1N1S3N3amNEU'),
	(160, 'Lobo Wildlife Lodge', 'https://test.safaribookings.com/dev-test-link/NJVDU3bmF0eG8zVXFhd3EvU0lCT2c9PSIsInZhbHVlIjoiM1lJcFB3MjVmVkRpVVZLajc0Z0NNV'),
	(161, 'Mapito Tented Camp', 'https://test.safaribookings.com/dev-test-link/BLaGZJQzU2d0FFSCttNzVBOGRwS0E9PSIsInZhbHVlIjoicXd4bXpsYkFuTGFzM1BZL3FqamNMN'),
	(162, 'Mbalageti Serengeti', 'https://test.safaribookings.com/dev-test-link/d4d3VMT01ZZzR4K2hWVlY3MmcwalE9PSIsInZhbHVlIjoiUFZjM0Zjc1hiNm1LQ1dFdHpsQkdsS'),
	(163, 'Mbuzi Mawe Serena Camp', 'https://test.safaribookings.com/dev-test-link/VCR2YvNFFldWJpWDRUei9PZGY0Y1E9PSIsInZhbHVlIjoidW55NmNPM0ZOOGg2R2dya0lxamhMa'),
	(165, 'Ndutu Safari Lodge', 'https://test.safaribookings.com/dev-test-link/JXSVZpVWQ3eHd2bkpXbjZxMmhQWEE9PSIsInZhbHVlIjoiOEFHS0ljSUZQODQ0aWJKUWpRdHZtM'),
	(166, 'Olakira Camp', 'https://test.safaribookings.com/dev-test-link/M3ZjNZSG9PVzJueExDcDVPTmVGNEE9PSIsInZhbHVlIjoiTU13cUNmVTFpemJQdGVWTThkY3hNa'),
	(167, 'Olduvai Camp', 'https://test.safaribookings.com/dev-test-link/hpeXE2WG14aCsyTjUxbXE4bFduOUE9PSIsInZhbHVlIjoiV0FMcmE4YWZ4dXJ4OEthemFXeHA3b'),
	(169, 'Singita Sabora Tented Camp', 'https://test.safaribookings.com/dev-test-link/53cCtGeW14MVNCNnFhZlpDR2FWbHc9PSIsInZhbHVlIjoiNU8zL0tiUkFCaWlTZ1I5Q3IreGtYV'),
	(170, 'Singita Sasakwa Lodge', 'https://test.safaribookings.com/dev-test-link/V5QThsR3ZBTG9xbTQ0RWpHRlExM3c9PSIsInZhbHVlIjoiTUdrMDlJQlFMTWEvSXBaaFMwa3FZR'),
	(171, 'Sayari Camp', 'https://test.safaribookings.com/dev-test-link/hJMjJpSklQRUZqSHNXVEtUOENsa0E9PSIsInZhbHVlIjoiclhibTNQQjJpam1Ia1N2eUk2NXVOQ'),
	(172, 'Serengeti Bushtops', 'https://test.safaribookings.com/dev-test-link/BNcldXT1JyaFE3QkZxcHNJN0JWOFE9PSIsInZhbHVlIjoiaS91UVNnWTZUMzl6T2dVV1RLanRPQ'),
	(173, 'Serengeti Kati Kati Tented Camp', 'https://test.safaribookings.com/dev-test-link/JtMm11ekRCREJWYmxzakFEUkZ1QXc9PSIsInZhbHVlIjoiZDFvV2N4MmJ1dlRQbUFXNDVocFlTV'),
	(175, 'Serengeti Migration Camp', 'https://test.safaribookings.com/dev-test-link/gyMTJ5clhxaWZyU0ljc3doSUs4dmc9PSIsInZhbHVlIjoiMGtscit0UEFhaTBQRkR0OWNqRzE0Y'),
	(176, 'Serengeti Safari Camp', 'https://test.safaribookings.com/dev-test-link/lhWUZYRU5CTCtRRFVodTZLVjJ0dnc9PSIsInZhbHVlIjoiQVNDdktlVkJuN21wOVFhYzhSVWxpS'),
	(177, 'Serengeti Savannah Camps', 'https://test.safaribookings.com/dev-test-link/U5RU1WYzh1OEpoU081KzQ1NFg4dHc9PSIsInZhbHVlIjoiV1FOcTY4MkVQMHY5dSsyLzJCS2pHa'),
	(178, 'Serengeti Serena Safari Lodge', 'https://test.safaribookings.com/dev-test-link/Y4Z3k5ejJtVlYzZmtkVmpFaXBqOHc9PSIsInZhbHVlIjoiWTZ4eHhLanBGWGthUDNyb3VHYUxLc'),
	(179, 'Serengeti Simba Lodge', 'https://test.safaribookings.com/dev-test-link/E2b0ZLV3paS1g2MmUrdU5rRy82anc9PSIsInZhbHVlIjoiUm1WaGNKQUhtM3ZCSHprNGhMK3VTT'),
	(180, 'Serengeti Sopa Lodge', 'https://test.safaribookings.com/dev-test-link/VKZ3VPR1M2U3pjbS80L1RxVk9NUHc9PSIsInZhbHVlIjoiTXk4ZDdQb2M0VGUxSWNwRmNzaWlGS'),
	(181, '&Beyond Serengeti Under Canvas', 'https://test.safaribookings.com/dev-test-link/hXVE54dGxlYWdwUk50L1ZJa1krOXc9PSIsInZhbHVlIjoiblcvcDRRcWlLQ3VndmFwOFRkcHZSV'),
	(182, 'Serengeti Wild Camp', 'https://test.safaribookings.com/dev-test-link/dQa21taVR4bDBlRmhWN3l1RFJhdXc9PSIsInZhbHVlIjoiaEsrNUlVbVRhRTRiWHdjQ0NraTFtY'),
	(183, 'Serengeti Wilderness Camp', 'https://test.safaribookings.com/dev-test-link/FmRVdtdUc3UzErbjBPRS9nL29zOFE9PSIsInZhbHVlIjoiRjhvVWpwMzNobk11R3FCV0N2NVBmS'),
	(184, 'Serian\'s Serengeti North', 'https://test.safaribookings.com/dev-test-link/BJdVJXNGJpclRUdlFnUGt2WWZhbGc9PSIsInZhbHVlIjoidG9NZ1JtL3RaT25pMGdSQ0RyTTFaS'),
	(185, 'Seronera Wildlife Lodge', 'https://test.safaribookings.com/dev-test-link/Q0a25aVzAwUW9sZjdIcHhLQjhUN2c9PSIsInZhbHVlIjoiemRJanhmTEhvbTJNeTI5Z1ZWUklnM'),
	(186, 'Simiyu Mobile Camp', 'https://test.safaribookings.com/dev-test-link/p2Z05vVm1MWVBBQ2xPdmZvOUNaZ1E9PSIsInZhbHVlIjoiYlM5dmlyYm1lR2oyVVFUSm1lQ09CZ'),
	(187, 'Mbali Mbali Soroi Serengeti', 'https://test.safaribookings.com/dev-test-link/c4emlSdmpNWGNacllBYVlIdm4wNEE9PSIsInZhbHVlIjoiRC95UDFZaFlSRmpRVEo1di85c0V0M'),
	(188, 'Ubuntu Migration Camp', 'https://test.safaribookings.com/dev-test-link/lnOXpIQUpLMlhnM28zUDE2RE1BS0E9PSIsInZhbHVlIjoiZ0pjUzY4ME9PMFVMOGxlS0NiS1hua'),
	(190, 'Vuma Hills Tented Camp', 'https://test.safaribookings.com/dev-test-link/VvbDJlOTI1alFVVll6MDYzc09haWc9PSIsInZhbHVlIjoiWEdYZDczTUN4WCt3WGVTckZwSlg2M'),
	(191, 'Mikumi Wildlife Camp', 'https://test.safaribookings.com/dev-test-link/A4eGFjNkRQK1BWWU93bjcrY0d6WHc9PSIsInZhbHVlIjoiTmJKK1ZxSWpiSFQ1SU9XM3l1SEY3V'),
	(192, 'Tan-Swiss Lodge', 'https://test.safaribookings.com/dev-test-link/1UU2oySWhpbEN4NTc0WTlqVlpRM0E9PSIsInZhbHVlIjoiUU9ib1VkSG5mWUVib3JVcVRRLytBQ'),
	(193, 'Jongomero', 'https://test.safaribookings.com/dev-test-link/NJSklQUVRnQjNVR1JRM2M3Y1d0dXc9PSIsInZhbHVlIjoiNXJSUFRKenVRN09wSW9KMUlPK3Z6Z'),
	(194, 'Kwihala Camp', 'https://test.safaribookings.com/dev-test-link/l4M1NYdmJGaFp4elVpRjNaZFdIaHc9PSIsInZhbHVlIjoidzFGbHR3d3ppVzVnMm9id2pkQ1pFN'),
	(195, 'Mdonya Old River', 'https://test.safaribookings.com/dev-test-link/BSbURyMU9SNENXNkJCdWt2NDh1aEE9PSIsInZhbHVlIjoiRzhxYWJhWmFQa1VtSFUwL1N6bE95K'),
	(196, 'Tandala Safari Camp', 'https://test.safaribookings.com/dev-test-link/ZqdzNSaHYxZCtwVXlpZDIyRDdDOHc9PSIsInZhbHVlIjoidG1xZklPcHJHY1ZTRW1PVHVodExDW'),
	(197, 'Ruaha Hilltop Lodge', 'https://test.safaribookings.com/dev-test-link/5qOExiK2hwZkxoNmExWjluaTJ5OWc9PSIsInZhbHVlIjoiT284OGhiU3lVR283azhPOXRzUmd0c'),
	(198, 'Mwagusi Safari camp', 'https://test.safaribookings.com/dev-test-link/MwWHlUaTY4TGs4N3ZmUWdFcTFOdkE9PSIsInZhbHVlIjoiaWYvZCtGa3RmSDRPZzFLczlVc2FJY'),
	(199, 'Ruaha River Lodge', 'https://test.safaribookings.com/dev-test-link/NVZWpTWjFxWDBld3F0aEp5OC9pRVE9PSIsInZhbHVlIjoickFHWUNWdXNBNkt0N3FuRkNJdUE3W'),
	(200, 'Sanctuary Swala Camp', 'https://test.safaribookings.com/dev-test-link/dmeEZGekN3djgzblplcjVqc2N5eWc9PSIsInZhbHVlIjoicnBqR05aMDFEYW1TUnBDRDdLVGY0d');

-- Structuur van  tabel safaribookings.operators wordt geschreven
CREATE TABLE IF NOT EXISTS `operators` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `website` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)  
) ENGINE=InnoDB AUTO_INCREMENT=4337 DEFAULT CHARSET=utf8;

INSERT INTO `operators` (`id`, `name`, `website`) VALUES
	(3, 'The Safari Partners', 'https://test.safaribookings.com/dev-test-link/huYTJQdEowenFBZzk2NDhzODhGdlE9PSIsInZhbHVlIjoiYjhYd05FbjVFelhtalcxSWlEcHJUd'),
	(177, 'Gondwana Tours & Safaris', 'https://test.safaribookings.com/dev-test-link/ovdHlveTdhS2dROTMxcmQreGZCM2c9PSIsInZhbHVlIjoicmtHTW85MjJUMWM3THgva2JmTnhaK'),
	(209, 'Pembury Tours', 'https://test.safaribookings.com/dev-test-link/Q1OVdzNFBKTktIVDJPZDB2SWhrd1E9PSIsInZhbHVlIjoibTZ5ampmdCtiSk5jVmtxOFVHRVRpU'),
	(410, 'Boundless Africa Journeys', 'https://test.safaribookings.com/dev-test-link/5Uc2VvMkdlNXhwWUswQm5pZlFDRmc9PSIsInZhbHVlIjoiMEF0TXlwUU43K1NKSkpBRUVQUzVIa'),
	(557, 'Zambezi Safari & Travel Co Ltd', 'https://test.safaribookings.com/dev-test-link/x1emFVTWRmcm1LVHNFL01FSjd0WFE9PSIsInZhbHVlIjoiZVB4TG5TMjBZQmlTSzYzMHF0cHFOU'),
	(575, 'Kenya Walking Survivors Safaris Ltd', 'https://test.safaribookings.com/dev-test-link/tOVlZlaGJ2STJCSkpkOXc4ZFFnQ2c9PSIsInZhbHVlIjoiWFdGMnpaenpoRDBhSWpscEwwaS91V'),
	(619, 'Compass Odyssey', 'https://test.safaribookings.com/dev-test-link/IyRytMSG1oaHM2RDdoMFo0VUNBdnc9PSIsInZhbHVlIjoiS0dZM2MrajUvTXN0eXdLRGVoMWFwc'),
	(620, 'Discover Africa', 'https://test.safaribookings.com/dev-test-link/83NTJ0TXo5NGFzc09wSW9ZeFB1Y2c9PSIsInZhbHVlIjoiVnRCUGxIanVBdUJoekdIMkEvZnp1M'),
	(663, 'E-Trip Africa', 'https://test.safaribookings.com/dev-test-link/hDLzdrSlFkbWFKWVBMeG9oS2xBQmc9PSIsInZhbHVlIjoiZ0ZZdnZkM2JlSjEyVVVtSWVaQ0xpN'),
	(693, 'Yellow Zebra Safaris', 'https://test.safaribookings.com/dev-test-link/VldzBiQUFteEtBd0pqRXRIcStsNFE9PSIsInZhbHVlIjoidFNVUXdFMlZxQkJsSXYvamtLV2lNN'),
	(694, 'African Paradise Safaris', 'https://test.safaribookings.com/dev-test-link/VnZnliUk4xamF4MTh0QXUzRjQyNUE9PSIsInZhbHVlIjoicnNWVTNtb25DakZvak1uRlNzNld0U'),
	(696, 'Afrishare Trekking & Safaris', 'https://test.safaribookings.com/dev-test-link/dyVHdUYjQweWZhUlRmQmk2ZVVId3c9PSIsInZhbHVlIjoiQzFlVENzR2NWNkVsWWRNcTJ3dHRha'),
	(750, 'Giltedge', 'https://test.safaribookings.com/dev-test-link/FzSGpXajB6akl1aEp4WW1tdUlPamc9PSIsInZhbHVlIjoibVIwdTZrQkFaYW45MXd2bXNiU2xmS'),
	(788, 'Indigo Safaris', 'https://test.safaribookings.com/dev-test-link/hHWWtTb2Y3aW1LYitpWGFMeGFvSEE9PSIsInZhbHVlIjoiWWlSTHd6WktkK3NUNmRsSy9BRlU1N'),
	(798, 'Wildebeest Safaris LTD', 'https://test.safaribookings.com/dev-test-link/U3SXdrN1RxVXlSdjE2OGpzTFJGSlE9PSIsInZhbHVlIjoiRnNQUlVSRzRPVkswRXVTYlFqeURPQ'),
	(801, 'Right Choice Tours & Safaris', 'https://test.safaribookings.com/dev-test-link/tId0NiQ3ZhSUF6TXBrK04rN1VidUE9PSIsInZhbHVlIjoiOWJGT1JIYlU2dmc3RktvVkpHNW1NY'),
	(807, 'Regional Tours & Safaris Ltd', 'https://test.safaribookings.com/dev-test-link/I1S1NHbzhQbFg0N2xMNU91STFrVEE9PSIsInZhbHVlIjoiWEdmbXVqdmJsRnlsUnBHcTBvcG9LV'),
	(1135, 'Go2Africa', 'https://test.safaribookings.com/dev-test-link/o0d2M2K2NpVjJyRm1CVjZPL1JBcEE9PSIsInZhbHVlIjoieXFuRG9tT1k5eGN4c2VmcnVPUFl4U'),
	(1517, 'Uhuru Travel & Tours', 'https://test.safaribookings.com/dev-test-link/tTaFR0YThDb3p5U0dOVHRZTmoyN2c9PSIsInZhbHVlIjoiTzRIZUpqKzd5TnNIRTdneStHTDRMQ'),
	(1586, 'Karibu Safaris In Kenya', 'https://test.safaribookings.com/dev-test-link/djcSt3d1dkZXN2b2pGNVFUeEtUNFE9PSIsInZhbHVlIjoiUUdUQmNHa3N0dHlqM0YzQk9zNWQ4a'),
	(1683, 'Earthlife Expeditions', 'https://test.safaribookings.com/dev-test-link/dOVGxqYXR3VFJ1dUR4WVFsYTY3cFE9PSIsInZhbHVlIjoiZkxjRGNZMTRKZkErbm9ScW1HUlN6d'),
	(1687, 'Safarihub', 'https://test.safaribookings.com/dev-test-link/w3MTV3UTVCOEhDOEsrQ2U4SENGeWc9PSIsInZhbHVlIjoiSVpFSmlLaXhLL0ZVZWtqNFNVR1lTd'),
	(1701, 'Ker & Downey Africa', 'https://test.safaribookings.com/dev-test-link/J5dG9HTVRQeEg3SGV5NWc0TTlOR2c9PSIsInZhbHVlIjoiQ2p5YW5UN2VvbkFDWmtMSnBMdDlPW'),
	(1750, 'Seven By Far Travel', 'https://test.safaribookings.com/dev-test-link/VzZUp6dHN5TmlVZWNpQzh0dnMzVmc9PSIsInZhbHVlIjoiMG5xdE41YkZaWi8wYVBzUlpPR2RMS'),
	(1786, 'Mamaland Safaris', 'https://test.safaribookings.com/dev-test-link/dKMW9RMTNJSGg1bFVLVXBCbjhrWWc9PSIsInZhbHVlIjoiR0tKRytuL0hidnFZN2xLdXhKdVN6U'),
	(1829, 'Tanzania Mwangaza Safari', 'https://test.safaribookings.com/dev-test-link/o0QkZEZ3NuT2RYMjM3UitPM3Jxcnc9PSIsInZhbHVlIjoiSExEWmFpZXhlN25vdFphS1pOalo5M'),
	(1859, 'Beacon Safaris', 'https://test.safaribookings.com/dev-test-link/1oN1lWZUVZekRkTENVeTkwd2gzcFE9PSIsInZhbHVlIjoiaVIvOFp6OUNuUjhTOXh4OHNnYW9lM'),
	(1962, 'Benson Safaris Tanzania', 'https://test.safaribookings.com/dev-test-link/4xV2RDOEhpL2pxUER0TFlhNUtVc2c9PSIsInZhbHVlIjoiaXdQN2lTTUoxNlU1ZmhqeGpNT2F5T'),
	(1988, 'Safari With Us', 'https://test.safaribookings.com/dev-test-link/l6Z29zTkU5ZjVkUWY1UlA2dUc0Z1E9PSIsInZhbHVlIjoiSTZpNVNvc2tRWkpaeTVEZ2RNRzFuM'),
	(2109, 'Kruger Park Tours', 'https://test.safaribookings.com/dev-test-link/xOeEZRVHpzbkFaRjdDdmMwN2RaK1E9PSIsInZhbHVlIjoiMFBUSTBCdmFSTXR0aFhWSlJkUlNwT'),
	(2220, 'Viva Safaris', 'https://test.safaribookings.com/dev-test-link/JnSUFBT0VXVGRZalV4MWFlYWY4UkE9PSIsInZhbHVlIjoiSUY5THNNUWZUeVlmc0VCNnRTaWVPZ'),
	(2308, 'Trip Advisor Africa Safaris', 'https://test.safaribookings.com/dev-test-link/R1bHN6QVNDbUZWMDhYK0VaN2ZWb3c9PSIsInZhbHVlIjoiYnBMYnNha3ppZi8rQmNEdG1EZjBwM'),
	(2335, 'Jewel of Africa Safaris', 'https://test.safaribookings.com/dev-test-link/IzWVFJWXNiRDBkZ3B4TUVSVTNOcEE9PSIsInZhbHVlIjoiK2c1QlZzWUU1NW1JSGNmeUxMRUxEU'),
	(2378, 'Kruger Park Travel ', 'https://test.safaribookings.com/dev-test-link/95dEo1LzRjcENJWTJhc2FBdnpDbVE9PSIsInZhbHVlIjoiaFFETFRUT0dNdExvQldDTnpGQ3F0d'),
	(2399, 'Amazing Memories Safaris', 'https://test.safaribookings.com/dev-test-link/E2TnZqTFpRVVB4UW5uVFBoZ2cxL1E9PSIsInZhbHVlIjoic3FRNWNBeDd0NmV2NjVmSUw4Nkt6T'),
	(2521, 'Shemeji Safari Tanzania', 'https://test.safaribookings.com/dev-test-link/xCMS9ERXo1K2xFeVpwR1Nta09MYXc9PSIsInZhbHVlIjoiVFFqbHNXdEdzZjRrQXJacWtBc0VmU'),
	(2583, 'Home To Africa Tours and Travel', 'https://test.safaribookings.com/dev-test-link/ZoTk03ajFBSUhWK0dKSFRxaUhJa0E9PSIsInZhbHVlIjoiUmFkM2RDd0lyK29OR0NYRlFSM0NDS'),
	(2586, 'Axis Africa Expedition & Safaris', 'https://test.safaribookings.com/dev-test-link/ZMUlJxdzE1VEZXQUlicmV0NThYUGc9PSIsInZhbHVlIjoicmZEZVVKUUcySVA4UHdDLzNJRHZUe'),
	(2673, 'Lion King Adventures', 'https://test.safaribookings.com/dev-test-link/V6ZUQ4VVI5ZkVNZSsvdHZMNUMrcmc9PSIsInZhbHVlIjoiNjQ2VEV5OWhWRWp6L1hDMjBKb1ZqU'),
	(2721, 'Classic Journeys Africa', 'https://test.safaribookings.com/dev-test-link/ZZbHQrbkVnMDNxQkpiOGEzVy8veWc9PSIsInZhbHVlIjoiNHh3K1RWNmJsQWlJaXk0eWZ3Q0JPY'),
	(2750, 'Unlimited Expeditions - The Soul of Tanzania', 'https://test.safaribookings.com/dev-test-link/oyYnMwalVhOE9xRk82b1pTOTRQMVE9PSIsInZhbHVlIjoiRzJIWER6NEo2UDdYUHkvUUN1d2FIY'),
	(2770, 'TravelPartners ', 'https://test.safaribookings.com/dev-test-link/BMemIyVFRYeEtOUU1XSExHTVdVOEE9PSIsInZhbHVlIjoiSmtIOTk5TWJsQnI5VFp0NzhyRG1EZ'),
	(2816, 'Features Africa Journeys', 'https://test.safaribookings.com/dev-test-link/sveVZaSnFGZHpZNWJka0dGeElyMmc9PSIsInZhbHVlIjoiMEVkZ1NTLy9TUlJkbHJoVXlsUGx4a'),
	(2992, 'Selous Ngalawa Camp', 'https://test.safaribookings.com/dev-test-link/ZTbDFSTVp5emM0WFJxMXZ6d0pjYmc9PSIsInZhbHVlIjoiaGMrRGZUNEdRaHl2N0IxWlFQSWlwV'),
	(3040, 'Suricata Safaris', 'https://test.safaribookings.com/dev-test-link/VBRmVyNDhuaXBLV0JRT0ZBU3FKTFE9PSIsInZhbHVlIjoiUXhHZFFTcU1IOStBZVJMcEkxTFVCZ'),
	(3099, 'Spirit of Kenya', 'https://test.safaribookings.com/dev-test-link/w4bnp4eVN5cUNvaWdOdVhxMFVyYUE9PSIsInZhbHVlIjoickVETlIxYjNzY3ppQkZUQVJWTisyM'),
	(3101, 'Wayfairer Travel', 'https://test.safaribookings.com/dev-test-link/5SM1V5WE0vN3gvcEF5YU8xbjcvVlE9PSIsInZhbHVlIjoibUFNYlJaTXlnVS8xR1FsZmNNUlp2N'),
	(3273, 'Orongai Africa Safari', 'https://test.safaribookings.com/dev-test-link/xqcTV1WVJXQmpMQzFIWkNwK2JnQ0E9PSIsInZhbHVlIjoiQXJTNk9xdElaWEFRQnJ3TjNlQjl6M'),
	(4336, 'SafariOffice', 'https://test.safaribookings.com/dev-test-link/BVc1ZXNG5WenQ1a0pCY2JVeW1lTkE9PSIsInZhbHVlIjoiejkxSHRkdjdYTGpUMGFEWmxieDZ6T');
